<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="../css/style.css"  />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../css/normalize.css"  />
  <script src="https://kit.fontawesome.com/00fca59a8b.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  <title>David ELT coaching</title>

  <!-- Fonctions utilitaires -->
  <script src="../js/utilities.js"></script>


</head>
<body>

  <!-- Header -->
  <header>

    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #3A5199;" >
      <a class="navbar-brand" href="acceuil.html" style="color: white;">David ELT coaching</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="acceuil.html" style="color: white;" >Acceuil <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="qui.html" style="color: white;" >Qui suis je ?</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link " href="programme.html" tabindex="-1" aria-disabled="true" style="color: white;" >Programme</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link " href="contact.html" tabindex="-1" aria-disabled="true" style="color: white;" >Contact</a>
          </li>

        </ul>

      </div>
    </nav>
  </header>
  <!-- Main -->
  <main>

    <!-- Carrousel -->
    <div class="carrousel ">
      <figure id="slider" class="slider reveal-1">
        <img src="" alt="Photo du carrousel" height="50%" width="50%" class="reveal-2">
        <figcaption class="reveal-3"></figcaption>
      </figure>
    </div>




      <!-- Presentation -->
      <div class="color reveal ">
      <div class="presentation ">
        <img src="images/david2.jpg" alt="photo" height="25%" width="25%" id="davun" class="reveal-1">
        <h1 class="reveal-2">David El Tahriri</h1>
        <h4 class="reveal-3"> Je suis le coach qui s'adaptera de maniére optimal a tout vos objectif </h4>
        <p class="reveal-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>

    <!-- Programme -->
    <div class="Programme ">
      <div class="Programmeun reveal-1" >
        <h2 class="reveal-1">Programme sur mesure</h2>
        <i class="fas fa-dumbbell reveal-2"></i>
        <p class="reveal-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint.</p>
        <a href="programme.html" class="reveal-4">Plus d'infos</a>
      </div>

      <div class="Programmedeux reveal-1 " >
        <h2  class="reveal-1">Suivis nutritionelle </h2>
        <i class="fas fa-utensils reveal-2"></i>
        <p  class="reveal-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint.</p>
        <a href="programme.html"  class="reveal-4">Plus d'infos</a>
      </div>

      <div class="Programmetrois reveal-1" >
        <h2 class="reveal-1">Suivis complet</h2>
        <i class="fas fa-weight reveal-2"></i>
        <p class="reveal-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint.</p>

        <a href="programme.html" class="reveal-4">Plus d'infos</a>
      </div>
    </div>

  </main>

  <!-- Footer -->
  <footer>
    <div class="footerflex">
      <div id="footerleft">
        <h3>Mes Reseaux</h3>
        <a href="#"> <i class="fab fa-instagram"></i></a>
        <a href="#">  <i class="fab fa-facebook"></i></a>
      </div>
      <div id="ml">
        <a href="#">Mentions Legales</a>
        <br>
        <br>
        <a href="#">CGU</a>
      </div>
      <div id="footerright">
        <h3>Newsletter</h3>
        <p>Inscrit toi je t'envoie des tonnes de conseille muscu !</p>
        <form class="" action="index.html" method="get">
          <input type="email" name="email" value="Ton mail ici !">
          <input type="submit" name="Newsletter" value="GO">
        </form>
      </div>


    </div>
  </footer>

  <script src="../js/carrousel.js"></script>
  <script src="../js/scrollspy.js"></script>


</body>
</html>
